spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        - id: library-service
          uri: http://library-service:8070
          predicates:
            - Path=/libraries/**